### ISSUE TITLE
Error when install.sh is executed

### ISSUE THREAD

**Issue by helson73** [torch/distro#136]
When I run install.sh as the tutorial recommended, but following errors rises.

Installing Lua version: LUAJIT21
CMake Error at exe/luajit-rocks/luajit-2.1/CMakeLists.txt:156 (MESSAGE):
  Cannot compile a useful lua.

  Function dlopen() seems not to be supported on your platform.

  Apparently you are not on a Windows platform as well.

  So lua has no way to deal with shared libraries!

And I can't find solution from googling, anyone can help please?
SYSTEM: Ubuntu 14.04 LTS server 64bit

**Comment by soumith** [comment]
./clean.sh
./install.sh

that should fix it.

**Comment by JupyterJones** [comment]
@soumith It does not fix it . The commands did nothing but repeat the warning.

**Comment by mememimis** [comment]
Actually in my case @soumith 's answer fixed my problem.
